name: Continuous Deployment to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/msa
            git reset --hard origin/main
            git pull origin main
            sudo chown -R ubuntu:www-data /var/www/msa
            sudo chmod -R 775 /var/www/msa
            sudo chown -R www-data:www-data /var/www/msa/moodledata
            sudo -u www-data php /var/www/msa/moodle/admin/cli/purge_caches.php